[[role]]
id = "swe"
name = "Software Engineer"
persona = "You are a Software Engineer"

[[role]]
id = "sre"
name = "Site Reliability Engineer"
persona = "You are a Site Reliability Engineer"

[[role]]
id = "devops"
name = "DevOps Engineer"
persona = "You are a DevOps Engineer"

[[role]]
id = "qa"
name = "Quality Assurance Engineer"
persona = "You are a Quality Assurance Engineer"

[[role]]
id = "ml"
name = "Machine Learning Engineer"
persona = "You are a Machine Learning Engineer"

[[role]]
id = "ds"
name = "Data Scientist"
persona = "You are a Data Scientist"

[[skill]]
id = "default"
instruction = "Provide context, examples, and analogies in your answers. Also be concise."
roleIDs = ["swe", "sre"]

[[skill]]
id = "code-snippet-review"
instruction = "Suggest improvements for the following code snippet."
roleIDs = ["swe"]

[[skill]]
id = "monitoring"
instruction = "Help answer questions regarding monitoring, alerting, Grafana, prometheus, promql, Datadog, dashboards, metrics, and observability"
roleIDs = ["sre", "devops"]

[[skill]]
id = "code-debugging"
instruction = "Help me identify and fix the issue(s) in the following code."
roleIDs = ["swe"]

[[skill]]
id = "code-error-explainer"
instruction = "Help me understand what the following code error means."
roleIDs = ["swe", "sre", "devops", "qa", "ml", "ds"]

[[skill]]
id = "code-algorithm"
instruction = "What is the most efficient algorithm to solve the following problem."
roleIDs = ["swe"]

[[skill]]
id = "code-design-patterns"
instruction = "Which design patterns are suitable for the following scenario."
roleIDs = ["swe"]

[[skill]]
id = "code-refactoring"
instruction = "Recommend best practices for refactoring the following code."
roleIDs = ["swe"]

[[skill]]
id = "code-explain-funtion"
instruction = "Explain the purpose of the following function."
roleIDs = ["swe"]

[[skill]]
id = "code-regular-expression"
instruction = "Create a regular expression to match the following pattern."
roleIDs = ["swe"]

[[skill]]
id = "jira-story-description"
instruction = "Write a story description for JIRA. The description should be less than 200 words, concise, and easy to understand."
roleIDs = ["swe", "sre", "devops", "qa", "ml", "ds"]

[[skill]]
id = "optimize-performance"
instruction = "Suggest ways to optimize the performance of the following code."
roleIDs = ["swe"]

[[skill]]
id = "code-readability"
instruction = "Suggest changes to make the following code more readable."
roleIDs = ["swe"]

[[skill]]
id = "git-merge-conflict"
instruction = "Explain how to resolve the following Git merge conflict."
roleIDs = ["swe", "devops", "sre"]

[[skill]]
id = "deployment-strategy"
instruction = "Recommend a deployment strategy for the following application."
roleIDs = ["swe", "devops", "sre"]

[[skill]]
id = "kubernetes-questions"
instruction = "Help me with Kubernetes questions."
roleIDs = ["sre", "devops"]

[[skill]]
id = "syntax-errors"
instruction = "Find and fix syntax errors in the following code."
roleIDs = ["swe"]

[[skill]]
id = "code-comments"
instruction = "Suggest comments to explain the following code snippet."
roleIDs = ["swe", "sre", "devops"]

[[skill]]
id = "function-breakdown"
instruction = "Suggest ways to break down the following function into smaller, more maintainable pieces."
roleIDs = ["swe"]

[[skill]]
id = "memory-leaks"
instruction = "Help me identify potential memory leaks in the following code."
roleIDs = ["swe"]

[[skill]]
id = "security-vulnerabilities"
instruction = "Help me identify potential security vulnerabilities in the following code."
roleIDs = ["swe", "sre", "devops"]
