# [[validation]]
# name = "email"
# pattern = '''\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b'''
#
# [[validation]]
# name = "social security number"
# pattern = '''\b\d{3}-\d{2}-\d{4}\b'''
#
# [[validation]]
# name = "phone number"
# pattern = '''\b(\d{3}[-.\s]??\d{3}[-.\s]??\d{4})\b'''
#
# [[validation]]
# name = "credit card number"
# pattern = '''\b(?:\d[ -]*?){13,16}\b'''
